### ISSUE TITLE
Are there research results?

### ISSUE THREAD

**Issue by huangtao36** [jsassenscheidt/mimic4-fnc#1]
I am very interested in this research. I want to know if you are doing further research and are there any research results that can be displayed?

**Comment by jsassenscheidt** [comment]
The work is a little bit on "hold" because I am waiting until the mimic-iv concepts can be build for PostgreSQL. Meanwhile I try to evaluate the model with the [Amsterdam UMC database](https://github.com/AmsterdamUMC/AmsterdamUMCdb)
